name: 'git-carbon'
description: "Automatically open PRs with `git-carbon update`"
runs:
  using: "composite"
  steps:
    - name: "Run git-carbon update --all"
      shell: bash
      run: go run github.com/mullvad/git-carbon@latest update --all
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
